--task1
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES);

--task2
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

--task3
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY = (SELECT MIN(SALARY) FROM EMPLOYEES);

--task4
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY = (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=20);

--task5
SELECT FIRST_NAME,LAST_NAME, EMPLOYEE_ID, HIRE_DATE FROM EMPLOYEES
WHERE HIRE_DATE = (SELECT MAX(HIRE_DATE) FROM EMPLOYEES);

--task6
SELECT FIRST_NAME,LAST_NAME, EMPLOYEE_ID, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE LOCATION_ID=1700);

--task7
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, JOB_ID FROM EMPlOYEES
WHERE JOB_ID IN (SELECT JOB_ID FROM EMPLOYEES WHERE DEPARTMENT_ID=80);

--task8
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY > ALL (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID='SH_CLERK');

--task9
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY FROM EMPLOYEES
WHERE SALARY < ANY (SELECT SALARY FROM EMPLOYEES WHERE JOB_ID='IT_PROG');

--task10
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, DEPARTMENT_ID FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (SELECT DEPARTMENT_ID FROM DEPARTMENTS WHERE DEPARTMENT_NAME LIKE '%Sales%');

--task11
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES E
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=E.DEPARTMENT_ID);

--task12
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY, DEPARTMENT_ID FROM EMPLOYEES E
WHERE SALARY = (SELECT MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID=E.DEPARTMENT_ID) ORDER BY SALARY ASC;

--task13
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, SALARY, JOB_ID FROM EMPLOYEES E
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES WHERE JOB_ID=E.JOB_ID);

--task14
SELECT EMPLOYEE_ID, FIRST_NAME, HIRE_DATE, DEPARTMENT_ID FROM EMPLOYEES E
WHERE HIRE_DATE > (SELECT MIN(HIRE_DATE) FROM EMPLOYEES WHERE DEPARTMENT_ID=E.DEPARTMENT_ID);

--task15 
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID, MANAGER_ID FROM EMPLOYEES E
WHERE EXISTS (SELECT 1 FROM EMPLOYEES WHERE E.EMPLOYEE_ID=MANAGER_ID);

--task16
SELECT FIRST_NAME, LAST_NAME, EMPLOYEE_ID FROM EMPLOYEES E
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES WHERE E.EMPLOYEE_ID=MANAGER_ID);

--task17
SELECT DEPARTMENT_NAME, DEPARTMENT_ID FROM DEPARTMENTS D
WHERE NOT EXISTS (SELECT 1 FROM EMPLOYEES E WHERE D.DEPARTMENT_ID=E.DEPARTMENT_ID);

--task18
SELECT DEPARTMENT_NAME, DEPARTMENT_ID FROM DEPARTMENTS D
WHERE EXISTS (SELECT 1 FROM EMPLOYEES E WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID AND E.SALARY>10000);

--task19
SELECT DEPARTMENT_ID, (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID=DEPT_STATS.DEPARTMENT_ID) AS DEPT_NAME, AVG_SALARY
FROM (SELECT DEPARTMENT_ID, ROUND(AVG(SALARY),1) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT_ID) DEPT_STATS
WHERE AVG_SALARY>8000;

--task20
SELECT DEPARTMENT_ID, (SELECT DEPARTMENT_NAME FROM DEPARTMENTS D WHERE D.DEPARTMENT_ID=DEPT_STATS.DEPARTMENT_ID) AS DEPT_NAME, AVG_SALARY
FROM (SELECT ROUND(AVG(SALARY),1) AS AVG_SALARY, DEPARTMENT_ID FROM EMPLOYEES GROUP BY DEPARTMENT_ID) DEPT_STATS
ORDER BY AVG_SALARY DESC
FETCH FIRST 3 ROWS ONLY;