--task1
SELECT E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--task2
SELECT E.FIRST_NAME, E.LAST_NAME, J.JOB_TITLE FROM EMPLOYEES E
JOIN JOBS J ON E.JOB_ID=J.JOB_ID;

--task3
SELECT FIRST_NAME, LAST_NAME, LOCATION_ID FROM EMPLOYEES 
JOIN DEPARTMENTS USING (DEPARTMENT_ID) JOIN LOCATIONS USING (LOCATION_ID);

--task4
SELECT FIRST_NAME,LAST_NAME,DEPARTMENT_NAME FROM EMPLOYEES NATURAL JOIN DEPARTMENTS;

--task5
SELECT CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS EMP_NAME, CONCAT(M.FIRST_NAME,' ',M.LAST_NAME) AS MANAGER_NAME FROM EMPLOYEES E 
JOIN EMPLOYEES M ON E.MANAGER_ID=M.EMPLOYEE_ID;

--task6
SELECT CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS EMP_NAME, D.DEPARTMENT_NAME FROM EMPLOYEES E 
LEFT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--task7
SELECT CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS EMP_NAME, D.DEPARTMENT_NAME FROM EMPLOYEES E 
RIGHT JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;

--task8
SELECT CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS EMP_NAME, D.DEPARTMENT_NAME FROM EMPLOYEES E
CROSS JOIN DEPARTMENTS D;

--task9
SELECT EMPLOYEE_ID FROM EMPLOYEES
UNION SELECT EMPLOYEE_ID FROM JOB_HISTORY;

--task10
SELECT EMPLOYEE_ID FROM EMPLOYEES
INTERSECT 
SELECT EMPLOYEE_ID FROM JOB_HISTORY;

--task11
SELECT CONCAT(E.FIRST_NAME,' ',E.LAST_NAME) AS EMP_NAME, D.DEPARTMENT_NAME, L.CITY FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID
JOIN LOCATIONS L ON D.LOCATION_ID=L.LOCATION_ID;

--task12
CREATE VIEW EMP_DEPT_VIEW AS 
SELECT E.EMPLOYEE_ID, E.FIRST_NAME, E.LAST_NAME, D.DEPARTMENT_NAME FROM EMPLOYEES E
JOIN DEPARTMENTS D ON E.DEPARTMENT_ID=D.DEPARTMENT_ID;
SELECT * FROM EMP_DEPT_VIEW;

--task13
CREATE VIEW RICH_EMPS AS
SELECT * FROM (SELECT CONCAT(FIRST_NAME,' ',LAST_NAME) AS EMP_NAME, SALARY FROM EMPLOYEES)
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);
SELECT * FROM RICH_EMPS;

--task 14
SELECT * FROM EMPLOYEES E
WHERE E.EMPLOYEE_ID IN (SELECT EMPLOYEE_ID FROM EMPLOYEES MINUS SELECT EMPLOYEE_ID FROM JOB_HISTORY);
--this can only be done with the subquery but Q says display employees, not display employee id