--Task1
SELECT * FROM EMPLOYEES
WHERE SALARY > 9000;

--Task2
SELECT * FROM EMPLOYEES
WHERE HIRE_DATE < '02-JAN-2010';


--Task3
SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID BETWEEN 30 AND 70;

--Task4
SELECT * FROM EMPLOYEES
WHERE SALARY BETWEEN 4000 AND 10000;

--Task5
SELECT * FROM EMPLOYEES
WHERE commission_pct IS NOT NULL;

--Task6
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'M%';

--Task 7
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%y';

--Task 8
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%an%';

--Task 9
SELECT * FROM EMPLOYEES
WHERE LENGTH(FIRST_NAME) = 6;

--Task 10
SELECT * FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'J%n'; 

--Task 11
SELECT * FROM EMPLOYEES
WHERE SALARY > 12000 AND DEPARTMENT_ID = 80;

--Task 12
SELECT * FROM EMPLOYEES
WHERE SALARY > 7000 OR DEPARTMENT_ID = 40;

--Task 13
SELECT * FROM EMPLOYEES
WHERE NOT (SALARY>6000);

--Task 14
SELECT * FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 30 OR DEPARTMENT_ID = 90) AND SALARY > 5000;

--Task 15
SELECT * FROM EMPLOYEES
WHERE SALARY < 20000 AND NOT (DEPARTMENT_ID = 50);

--Task 16
SELECT FIRST_NAME, LAST_NAME, CEIL(CURRENT_DATE - HIRE_DATE) AS TOTAL_DAYS
FROM EMPLOYEES;

--Task17
SELECT FIRST_NAME, LAST_NAME, HIRE_DATE, ADD_MONTHS(HIRE_DATE,6) AS CONTRACT_DATE
FROM EMPLOYEES;

--Task18
SELECT CURRENT_DATE FROM DUAL;

--Task19
SELECT FIRST_NAME,LAST_NAME, EXTRACT(MONTH FROM HIRE_DATE) AS hire_month, EXTRACT(YEAR FROM HIRE_DATE) AS hire_year
FROM EMPLOYEES;

--Task20
SELECT TO_DATE('2026-03-01', 'YYYY-MM-DD') - TO_DATE('2026-02-20', 'YYYY-MM-DD') AS DAY_DIFF FROM DUAL; 

--Task21
SELECT NULLIF(80,80) FROM DUAL;

--Task22
SELECT COALESCE(NULL,500,700) FROM DUAL;

--Task23
SELECT NVL(NULL,commission_pct) FROM EMPLOYEES;

--Task24
SELECT NVL(NULL,999) FROM DUAL;

--Task25
SELECT FIRST_NAME, TO_CHAR(SALARY,'$99,999,999') AS FORMATTED_SALARY FROM EMPLOYEES;