CREATE TABLE tasks (
    task_id NUMBER PRIMARY KEY,
    title VARCHAR2(255) NOT NULL UNIQUE,
    name VARCHAR2(100),
    start_date DATE, 
    due_date DATE,
    priority NUMBER(1) DEFAULT 3 NOT NULL,
    description CLOB
);

INSERT ALL
    INTO tasks (task_id, title, name, priority)
    VALUES (1, 'Database Design', 'Ali Khan', 1)
    INTO tasks (task_id, title, name, priority)
    VALUES (2, 'API Development', 'Sara Khan', 2)
    INTO tasks (task_id, title, name, priority)
    VALUES (3, 'Frontend UI', 'Hamid Ali', 3)
SELECT * FROM dual;

INSERT INTO TASKS(task_id, title, name, priority)
    VALUES(4,'Prepare HR Report',(SELECT FIRST_NAME FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101),2);

INSERT INTO TASKS(task_id,title) VALUES (5,'Partial Task');

SELECT * FROM TASKS;

SELECT TITLE,PRIORITY FROM TASKS
WHERE PRIORITY=2;

SELECT * FROM TASKS
WHERE TITLE LIKE '%Report%';

SELECT * FROM TASKS
ORDER BY TITLE ASC;

SELECT DISTINCT PRIORITY FROM TASKS;

UPDATE TASKS
SET PRIORITY=1 WHERE TASK_ID=2;

UPDATE TASKS
SET TITLE = 'UPDATE EMPLOYEE DATA' WHERE TASK_ID=5;

UPDATE TASKS
SET PRIORITY=2 WHERE PRIORITY=3;

SELECT COUNT(PRIORITY) FROM TASKS
GROUP BY PRIORITY
ORDER BY PRIORITY;

SELECT AVG(PRIORITY) AS avg_priority FROM TASKS;

SELECT MAX(PRIORITY) AS max_priority FROM TASKS;

SELECT PRIORITY, COUNT(*) FROM TASKS
WHERE TITLE LIKE '%Report%'
GROUP BY PRIORITY
ORDER BY PRIORITY;

SELECT COUNT(*) FROM TASKS
WHERE (PRIORITY>1);

SELECT PRIORITY, COUNT(*) FROM TASKS
GROUP BY PRIORITY
HAVING COUNT(*) > 2;    --u cant use aggregate function with WHERE and also cant use WHERE after grouping.

SELECT * FROM TASKS
ORDER BY TITLE;

SELECT * FROM TASKS
ORDER BY PRIORITY DESC, TITLE ASC;

SELECT * FROM TASKS
ORDER BY PRIORITY ASC;

INSERT INTO TASKS VALUES (SELECT * FROM tasks_archive);

INSERT INTO TASKS (task_id,title) VALUES (6,(SELECT FIRST_NAME FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101));